
plugins {
    id "java-library"
}

repositories {
    mavenCentral()
}

dependencies {

    implementation("org.slf4j:jcl-over-slf4j:1.7.20")
    implementation("ch.qos.logback:logback-classic:1.1.7")
    implementation("net.logstash.logback:logstash-logback-encoder:6.3")

    // Use JUnit Jupiter for testing.
    testImplementation("org.mockito:mockito-core:5.20.0")
    testImplementation("org.assertj:assertj-core:3.27.6")
    testImplementation("junit:junit:4.13.2")

    testImplementation("org.junit.jupiter:junit-jupiter:5.13.4")
}